# Digital Twin Platform — Task Runner
# Usage: make <target>

.PHONY: help up down reset logs \
        backend-shell db-shell redis-shell worker-shell \
        migrate migrate-create migrate-down migrate-history seed \
        test test-unit test-integration test-cov \
        lint format check-secrets \
        logs-backend logs-worker logs-frontend logs-db \
        queue-status queue-clear lock-clear queue-results \
        worker-up backend-up frontend-up \
        worker-restart backend-restart frontend-restart \
        redis-ui redis-ui-down \
        install-backend install-frontend dev-backend dev-frontend

# ─── Help ─────────────────────────────────────────────────────────────────────
help:
	@echo ""
	@echo "docbase — Development Task Runner"
	@echo "════════════════════════════════════════════════"
	@echo ""
	@echo "STACK"
	@echo "  make up                Start full stack (build + detach)"
	@echo "  make down              Stop all services"
	@echo "  make reset             Wipe volumes + full restart"
	@echo "  make logs              Tail all service logs"
	@echo "  make logs-backend      Tail backend logs only"
	@echo "  make logs-worker       Tail worker logs only"
	@echo "  make logs-frontend     Tail frontend logs only"
	@echo "  make logs-db           Tail database logs only"
	@echo ""
	@echo "SHELLS"
	@echo "  make backend-shell     bash in backend container"
	@echo "  make worker-shell      bash in worker container"
	@echo "  make db-shell          psql in db container"
	@echo "  make redis-shell       redis-cli in redis container"
	@echo ""
	@echo "QUEUE / JOBS (ARQ + Redis)"
	@echo "  make queue-status      Show queued, in-progress jobs and active locks"
	@echo "  make queue-clear       Nuke all ARQ jobs, locks, retry keys"
	@echo "  make lock-clear        Clear only memory_lock:* keys (unblock extraction)"
	@echo "  make queue-results     Show recent job results (last 20)"
	@echo "  make redis-ui          Start Redis Commander UI at http://localhost:8081"
	@echo "  make redis-ui-down     Stop Redis Commander"
	@echo ""
	@echo "DATABASE"
	@echo "  make migrate           Apply all pending migrations"
	@echo "  make migrate-create    Generate a new autogenerated migration"
	@echo "  make migrate-down      Roll back one migration"
	@echo "  make migrate-history   Show migration history"
	@echo "  make seed              Seed dev database"
	@echo ""
	@echo "TESTS"
	@echo "  make test              Run backend unit tests (matches CI)"
	@echo "  make test-unit         Same as test, verbose"
	@echo "  make test-integration  Postgres-backed integration suite (requires `make up`)"
	@echo "  make test-cov          Unit tests with pytest-cov over `app/`"
	@echo ""
	@echo "CODE QUALITY"
	@echo "  make lint              Run ruff + frontend linter"
	@echo "  make format            Auto-format backend + frontend"
	@echo "  make check-secrets     Scan for accidentally committed secrets"
	@echo ""
	@echo "CLOUD DEPLOY (after local checks)"
	@echo "  Full setup: docs/DEPLOY_SETUP_GUIDE.md"
	@echo "  1. make test           (or make test-unit) on your machine"
	@echo "  2. make up             optional: full Docker smoke before AWS"
	@echo "  3. ./scripts/deploy.sh dev     Terraform workspace dev + S3/CF"
	@echo "  4. GitHub: Actions → Deploy docbase → environment dev (same as 3 in CI)"
	@echo "  5. ./scripts/deploy.sh prod    only after dev URL + DOCBASE_VITE_API_URL verified"
	@echo ""

# ─── Docker ───────────────────────────────────────────────────────────────────
up:
	docker compose up --build -d
	@echo "Stack is up. Backend: http://localhost:8000 | Frontend: http://localhost:5173"

down:
	docker compose down

backend-up:
	docker compose up --build -d backend

frontend-up:
	docker compose up --build -d frontend

worker-up:
	docker compose up --build -d worker

db-up:
	docker compose up --build -d db

redis-up:
	docker compose up --build -d redis

backend-restart:
	docker compose restart backend

frontend-restart:
	docker compose restart frontend

worker-restart:
	docker compose restart worker

db-restart:
	docker compose restart db

redis-restart:
	docker compose restart redis

reset:
	docker compose down -v
	docker compose up --build -d

logs:
	docker compose logs -f

logs-backend:
	docker compose logs -f backend

logs-worker:
	docker compose logs -f worker

logs-frontend:
	docker compose logs -f frontend

logs-db:
	docker compose logs -f db

# ─── Shells ───────────────────────────────────────────────────────────────────
backend-shell:
	docker compose exec backend bash

worker-shell:
	docker compose exec worker bash

db-shell:
	docker compose exec db psql -U doctwin_user -d doctwin_db

redis-shell:
	docker compose exec redis redis-cli

# ─── Queue / Jobs ─────────────────────────────────────────────────────────────
queue-status:
	@echo ""
	@echo "── Queued jobs ──────────────────────────────"
	@docker compose exec redis redis-cli zrange arq:queue 0 -1 WITHSCORES 2>/dev/null || echo "  (queue empty)"
	@echo ""
	@echo "── In-progress jobs ─────────────────────────"
	@docker compose exec redis redis-cli keys "arq:in-progress:*" 2>/dev/null || echo "  (none)"
	@echo ""
	@echo "── Memory extraction locks ──────────────────"
	@docker compose exec redis redis-cli keys "memory_lock:*" 2>/dev/null || echo "  (none)"
	@echo ""
	@echo "── Retry-scheduled jobs ─────────────────────"
	@docker compose exec redis redis-cli keys "arq:retry:*" 2>/dev/null || echo "  (none)"
	@echo ""
	@echo "── Memory extraction locks ──────────────────"
	@docker compose exec redis redis-cli keys "memory_lock:*" 2>/dev/null || echo "  (none)"
	@echo ""

queue-clear:
	@echo "Clearing all ARQ jobs, results, locks, and retry keys..."
	@docker compose exec redis redis-cli eval "\
	  local keys = redis.call('keys', 'arq:*') \
	  for _, k in ipairs(keys) do redis.call('del', k) end \
	  local locks = redis.call('keys', 'memory_lock:*') \
	  for _, k in ipairs(locks) do redis.call('del', k) end \
	  return #keys + #locks" 0
	@echo "Done. Queue and locks cleared."

lock-clear:
	@echo "Clearing memory extraction locks..."
	@docker compose exec redis redis-cli eval "\
	  local locks = redis.call('keys', 'memory_lock:*') \
	  for _, k in ipairs(locks) do redis.call('del', k) end \
	  return #locks" 0
	@echo "Done."

queue-results:
	@echo ""
	@echo "── Recent job results (last 20) ─────────────"
	@docker compose exec redis redis-cli keys "arq:result:*" 2>/dev/null | head -20 | while read key; do \
	  echo ""; \
	  echo "  $$key"; \
	  docker compose exec redis redis-cli get "$$key" 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print('  status:', d.get('success','?'), '| fn:', d.get('function','?'), '| t:', d.get('finish_ms','?'));" 2>/dev/null || true; \
	done
	@echo ""

redis-ui:
	docker compose --profile dev-tools up -d redis-commander
	@echo "Redis Commander running at http://localhost:8081"

redis-ui-down:
	docker compose --profile dev-tools stop redis-commander

# ─── Database ─────────────────────────────────────────────────────────────────
migrate:
	docker compose exec backend alembic upgrade head

migrate-create:
	@read -p "Migration name: " name; \
	docker compose exec backend alembic revision --autogenerate -m "$$name"

migrate-down:
	docker compose exec backend alembic downgrade -1

migrate-history:
	docker compose exec backend alembic history --verbose

seed:
	docker compose exec backend env PYTHONPATH=/app python scripts/seed.py

# ─── Tests ────────────────────────────────────────────────────────────────────
test:
	docker compose exec backend pytest tests/unit

test-unit:
	docker compose exec backend pytest tests/unit -v

test-integration:
	docker compose exec backend pytest tests/integration -v

test-cov:
	docker compose exec backend pytest tests/unit --cov=app --cov-report=term-missing

# ─── Code Quality ─────────────────────────────────────────────────────────────
lint:
	docker compose exec backend ruff check app tests
	cd frontend && npm run lint

format:
	docker compose exec backend ruff format app tests
	cd frontend && npm run format

check-secrets:
	./scripts/check-secrets.sh

# ─── Local (no Docker) ────────────────────────────────────────────────────────
install-backend:
	cd backend && pip install -e ".[dev]"

install-frontend:
	cd frontend && npm install

dev-backend:
	cd backend && uvicorn app.main:app --reload --port 8000

dev-frontend:
	cd frontend && npm run dev
