/**
 * Shared layout styles for admin sub-pages (matches existing admin UI tokens).
 */
import type { CSSProperties } from "react";

export const adminStyles: Record<string, CSSProperties> = {
  page: {
    maxWidth: 1240,
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
    gap: 22,
  },
  hero: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 18,
    flexWrap: "wrap",
    padding: "30px",
    borderRadius: 24,
    background:
      "linear-gradient(135deg, rgba(79,70,229,0.1), rgba(15,23,42,0.05) 55%, rgba(255,255,255,0.92))",
    border: "1px solid rgba(79,70,229,0.15)",
  },
  eyebrow: {
    margin: 0,
    fontSize: 12,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: "var(--color-teal)",
  },
  title: {
    margin: "10px 0 0",
    fontFamily: "var(--font-display)",
    fontSize: 34,
    letterSpacing: "-0.03em",
    color: "var(--color-text-primary)",
  },
  subtitle: {
    margin: "12px 0 0",
    maxWidth: 720,
    fontSize: 15,
    lineHeight: 1.7,
    color: "var(--color-text-secondary)",
  },
  code: {
    fontSize: 13,
    padding: "2px 6px",
    borderRadius: 6,
    background: "rgba(15,23,42,0.06)",
  },
  refreshBtn: {
    padding: "10px 16px",
    borderRadius: 12,
    border: "1px solid var(--color-border)",
    background: "var(--color-surface)",
    fontWeight: 700,
    fontSize: 14,
    cursor: "pointer",
    color: "var(--color-text-primary)",
  },
  banner: {
    padding: "14px 18px",
    borderRadius: 14,
    background: "rgba(220,38,38,0.08)",
    border: "1px solid rgba(220,38,38,0.2)",
    color: "var(--color-text-primary)",
    fontSize: 14,
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
    gap: 14,
  },
  statCard: {
    padding: "20px 18px",
    borderRadius: 18,
    border: "1px solid var(--color-border)",
    background: "var(--color-surface)",
  },
  statLabel: {
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: "var(--color-text-tertiary)",
  },
  statValue: {
    marginTop: 8,
    fontSize: 28,
    fontWeight: 700,
    letterSpacing: "-0.02em",
    color: "var(--color-text-primary)",
  },
  statNote: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--color-text-secondary)",
  },
  panel: {
    padding: "22px 22px 26px",
    borderRadius: 20,
    border: "1px solid var(--color-border)",
    background: "rgba(255,255,255,0.96)",
  },
  panelHeader: {
    marginBottom: 8,
  },
  panelEyebrow: {
    margin: 0,
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: "var(--color-text-tertiary)",
  },
  panelTitle: {
    margin: "8px 0 0",
    fontSize: 20,
    fontWeight: 700,
    color: "var(--color-text-primary)",
  },
  panelBody: {
    margin: "12px 0 0",
    fontSize: 14,
    lineHeight: 1.65,
    color: "var(--color-text-secondary)",
  },
  chips: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  chip: {
    padding: "8px 12px",
    borderRadius: 999,
    fontSize: 13,
    background: "rgba(15,118,110,0.08)",
    border: "1px solid rgba(15,118,110,0.15)",
    color: "var(--color-text-primary)",
  },
  formRow: {
    marginTop: 14,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  label: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--color-text-secondary)",
  },
  input: {
    padding: "11px 14px",
    borderRadius: 12,
    border: "1px solid var(--color-border)",
    fontSize: 14,
    fontFamily: "ui-monospace, monospace",
  },
  inputEmail: {
    padding: "11px 14px",
    borderRadius: 12,
    border: "1px solid var(--color-border)",
    fontSize: 14,
    fontFamily: "inherit",
    maxWidth: 420,
  },
  actions: {
    marginTop: 18,
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
  },
  primaryBtn: {
    padding: "11px 18px",
    borderRadius: 12,
    border: "none",
    background: "var(--color-teal)",
    color: "#fff",
    fontWeight: 700,
    fontSize: 14,
    cursor: "pointer",
  },
  primaryBtnDisabled: {
    padding: "11px 18px",
    borderRadius: 12,
    border: "none",
    background: "var(--color-border)",
    color: "var(--color-text-tertiary)",
    fontWeight: 700,
    fontSize: 14,
    cursor: "not-allowed",
  },
  secondaryBtn: {
    padding: "11px 18px",
    borderRadius: 12,
    border: "1px solid var(--color-border)",
    background: "var(--color-surface)",
    fontWeight: 700,
    fontSize: 14,
    cursor: "pointer",
    color: "var(--color-text-primary)",
  },
  secondaryBtnDisabled: {
    padding: "11px 18px",
    borderRadius: 12,
    border: "1px solid var(--color-border)",
    background: "var(--color-surface)",
    fontWeight: 700,
    fontSize: 14,
    cursor: "not-allowed",
    color: "var(--color-text-tertiary)",
  },
  pre: {
    marginTop: 14,
    padding: 16,
    borderRadius: 14,
    fontSize: 12,
    lineHeight: 1.5,
    overflow: "auto",
    maxHeight: 420,
    background: "rgba(15,23,42,0.04)",
    border: "1px solid var(--color-border)",
  },
  errorText: {
    marginTop: 12,
    fontSize: 14,
    color: "#b91c1c",
  },
  successText: {
    marginTop: 12,
    fontSize: 14,
    color: "var(--color-teal-dim)",
  },
  panelHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 14,
    flexWrap: "wrap",
    marginBottom: 12,
  },
  tableWrap: {
    marginTop: 8,
    overflowX: "auto",
    borderRadius: 14,
    border: "1px solid var(--color-border)",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 13,
    minWidth: 560,
  },
  th: {
    textAlign: "left",
    padding: "12px 14px",
    borderBottom: "1px solid var(--color-border)",
    fontWeight: 700,
    color: "var(--color-text-secondary)",
    background: "rgba(15,23,42,0.03)",
  },
  td: {
    padding: "12px 14px",
    borderBottom: "1px solid var(--color-border)",
    color: "var(--color-text-primary)",
    verticalAlign: "middle",
  },
  tdMuted: {
    padding: "16px 14px",
    color: "var(--color-text-tertiary)",
    fontStyle: "italic",
  },
  badgeAdmin: {
    display: "inline-block",
    padding: "4px 10px",
    borderRadius: 999,
    fontWeight: 700,
    fontSize: 12,
    background: "rgba(79,70,229,0.12)",
    color: "#4338ca",
  },
  badgeMember: {
    display: "inline-block",
    padding: "4px 10px",
    borderRadius: 999,
    fontWeight: 600,
    fontSize: 12,
    background: "rgba(15,23,42,0.06)",
    color: "var(--color-text-secondary)",
  },
  linkBtn: {
    padding: "6px 12px",
    borderRadius: 8,
    border: "1px solid var(--color-teal)",
    background: "transparent",
    color: "var(--color-teal)",
    fontWeight: 700,
    fontSize: 12,
    cursor: "pointer",
  },
  linkBtnDanger: {
    padding: "6px 12px",
    borderRadius: 8,
    border: "1px solid rgba(220,38,38,0.4)",
    background: "transparent",
    color: "#b91c1c",
    fontWeight: 700,
    fontSize: 12,
    cursor: "pointer",
  },
  linkBtnDisabled: {
    padding: "6px 12px",
    borderRadius: 8,
    border: "1px solid var(--color-border)",
    background: "transparent",
    color: "var(--color-text-tertiary)",
    fontWeight: 700,
    fontSize: 12,
    cursor: "not-allowed",
  },
};
